(function(w){try{!function(a){function g(a,b){return f(a,b)}function f(a,b,c){g._select&&(typeof a=="string"||a.nodeName||a.length&&"item"in a||a==window)?(c=g._select(a,b),c.selector=a):c=isFinite(a.length)?a:[a];return e(c,f)}function e(a,b){for(var c in b)c!="noConflict"&&c!="_VERSION"&&(a[c]=b[c]);return a}function d(a,c){return b[a]=c}function c(a){var c=b[a]||window[a];if(!c)throw new Error("Requested module has not been defined.");return c}var b={};a.provide=d,a.require=c,e(g,{_VERSION:"0.2.5",ender:function(a,b){e(b?f:g,a)},fn:a.$&&a.$.fn||{}}),e(f,{forEach:function(a,b,c){for(c=0,l=this.length;c<l;++c)c in this&&a.call(b||this[c],this[c],c,this);return this},$:g});var h=a.$;g.noConflict=function(){a.$=h;return this},typeof module!="undefined"&&module.exports&&(module.exports=g),a.ender=a.$=g}(this),!function(){var a={exports:{}},b=a.exports;!function(b){var c,d,e,f=1,g,b=this,h=!1,i="postMessage",j="addEventListener",k=b[i];fn={},fn.postMessage=function(a,b,c){!b||(c=c||parent,k?c[i](a,b.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):b&&(c.location=b.replace(/#.*$/,"")+"#"+ +(new Date)+f++ +"&"+a))},fn.receiveMessage=function(a,f,i){k?(a&&(g&&receiveMessage(),g=function(b){if(typeof f=="string"&&b.origin!==f||typeof f=="function"&&f(b.origin)===h)return h;a(b)}),b[j]?b[a?j:"removeEventListener"]("message",g,h):b[a?"attachEvent":"detachEvent"]("onmessage",g)):(c&&clearInterval(c),c=null,a&&(i=typeof f=="number"?f:typeof i=="number"?i:100,e=document.location.hash,c=setInterval(function(){var b=document.location.hash,c=/^#?\d+&/;if(b!==d&&b!==e&&c.test(b)){d=b;var f=b.replace(c,"");e?f=f+"|"+e:f=f+"|",a({data:f})}},i)))},a.exports={postMessage:fn.postMessage,receiveMessage:fn.receiveMessage}}(window),provide("postmessage",a.exports),$.ender(a.exports)}()
var $VIZU6T=$.noConflict();var d=w.document,s={},ud='undefined',id=new Date().getTime(),r1,r2,n=navigator,ua=n.userAgent.toLowerCase(),u={},os,node,lang=n.browserLanguage||n.language,perm=true,base_dynamic='http://mono.vizu.com/',base_adpix='http://ohlone.vizu.com/',base_error='http://kato.vizu.com/',base_static='http://shasta.vizu.com/',passtarget=base_static+'v6/htm/passframe.html',base_vipix='http://ishi.vizu.com/',n_url_tag='http://secure-us.imrworldwide.com/cgi-bin/m',n_url_ssl='https://secure-us.imrworldwide.com/cgi-bin/m',n_acctID='nlsnci379',n_ty='js',n_mr='1',storageFrameTarget,vzcid=12264,ttype=7,l=d.location.href,adtype=1,nest=false,guid,guidOverride,pid='',pass=1,path='00/01/22/64/',iframe=0,fiframe=false,_i=null,preexp=7>0?1:0,postexp=preexp,impcnt=7,bannerUp=false,bannerURL,useLocalStorage=false,contentNodes=0,environment='',fv=0,viewableStatus=-1,aflag=0,dflag=0,vflag=0,agifLocked=false,agifPrimed=false,visible=4,viewableEnabled,viewableDiv,viewableLeft,viewableResponded=false,viewableDone=false,viewableGapCount=0;var all_nines='9999999999';do{r1=Math.floor(Math.random()*500);}while(r1<1||100<r1);do{r2=Math.floor(Math.random()*500);}while(r2<101||200<r2);id=Math.floor((id*r1)/r2);id=id.toString().substring(0,10);if(id.length<10){id=id+all_nines.substring(0,10-id.length);}
if(w.location.protocol=='https:'){base_dynamic=base_dynamic.replace(/http:/g,"https:");base_adpix=base_adpix.replace(/http:/g,"https:");base_error=base_error.replace(/http:/g,"https:");base_static=base_static.replace(/http:/g,"https:");passtarget=passtarget.replace(/http:/g,"https:");base_vipix=base_vipix.replace(/http:/g,"https:");n_url_tag=n_url_ssl;}
try{var fullScriptURL='http://mono.vizu.com/cdn/00/01/22/64/smart_tag.js?vzadid=fy15chefboyardee300x250&vzsid=rocketfuel&ord=[RANDOM]';if(fullScriptURL.indexOf('http:')!=-1){fullScriptURL=fullScriptURL.substring(7,fullScriptURL.length);}else{fullScriptURL=fullScriptURL.substring(8,fullScriptURL.length);}
s=d.getElementsByTagName('script'),k=s.length,node=null;while(k--){if(s[k].src!=null){if(s[k].src.indexOf(fullScriptURL)!=-1){node=s[k];s=s[k];break;}}}
if(node==null){s.src=null;}}catch(e){e.code=10;throw(e);}
var savethechildren='https://secure.savethechildren.org/site/c.8rKLIXMGIpI4E/b.6239401/k.C01C/Global_Action_Fund/apps/ka/sd/donor.asp?_ga=1.13695543.1073756496.1392330112&msource=weanlgaf0214&utm_source=nl&utm_medium=display&utm_campaign=nl-0214-brand';var psaObj={'300x250':[{'src':base_static+'v6/psa2014/300x250/300x250_save.jpg','href':savethechildren}],'728x90':[{'src':base_static+'v6/psa2014/728x90/728x90_save.jpg','href':savethechildren}],'160x600':[{'src':base_static+'v6/psa2014/160x600/160x600_save.jpg','href':savethechildren}],'300x600':[{'src':base_static+'v6/psa2014/300x600/300x600_save.jpg','href':savethechildren}],'120x600':[{'src':base_static+'v6/psa2014/120x600/120x600_save.jpg','href':savethechildren}]};try{var vzadid='fy15chefboyardee300x250',vzplid=escape(''),vzsid=escape('rocketfuel'),vzwc=escape(''),vzam=escape(''),vzc1=escape(''),vzc2=escape(''),vzc3=escape(''),vzc4=escape(''),vzc5=escape(''),vzc6=escape(''),vzc7=escape(''),vzc8=escape(''),vzc9=escape(''),vzc10=escape(''),vzwt='',vzsize='',vztc='',vzclick='',VZ_anonID='635F5618-5D32-78EB-AD74-22C914FBB327.1402529837',VZ_t='',VZ_s='',VZ_opt_out='';guid=VZ_anonID;guidOverride='';if(guidOverride!=''){guid=guidOverride;}
edge_lang='en',edge_ua='Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36';}catch(e){e.code=26;throw(e);}
var dataObj1={},qtags=[];try{dataObj1={"version":"7","tag":{"busterurl":"","mobile":0,"siteBlacklist":["asylum.com","bigdownload.com","breakingnews.com","chow.com","comicsalliance.com","cnbc.com","crunchbase.com","digg.com","divinecaroline.com","drugstore.com","drweil.com","engadget.com","everyblock.com","gadling.com","games.com","hoyts.com.au","juno.com","office.live.com","ohhappyday.com","mail.live.com","hotmail.com","play.it","joystiq.com","last.fm","luxist.com","massively.com","mayoclinic.com","mmgn.com","moviefone.com","naveen.net","netscape.aol.com","newsvine.com","ninemsn.com.au","officelive.com","online.wsj.com","popeater.com","premier.ticketek.com.au","primped.ninemsn.com.au","psychcentral.com","shoutcast.com","skinsight.com","streetlevel.com","switched.com","techcrunch.com","television.aol.com","thatsfit.com","theknot.ninemsn.com.au","truveo.com","tuaw.com","urlesque.com","walletpop.com","webmail.aol.com","wetpaint.com","wow.com","xbox.com","zone.msn.com"],"ctags":[0,0],"qtags":[{"id":"126945","flags":[0,0,0,0,0,0,0,0]},{"id":"126946","flags":[0,0,0,0,0,0,0,0]}],"intT":0.15,"intC":0.15,"sIntT":0.15,"sIntC":0.15,"sIntLevel":0,"sIntType":"banner","sAdBlacklist":[],"viewableImpression":0},"survey":{"box":{"bg":"63a1c6","border":"63a1c6","corners":1,"shadow":1,"color":"ffffff","line1":"One Question Site Survey","line2":"it takes only seconds to answer below","disclaimer":"","branding":1,"pp":1,"ppLink":"http://www.vizu.com/w3c/policy.htm","safe":1,"width":350,"height":1,"rtl":0},"coppa":{"enable":false,"text":"Are you 13 years of age or older?","yesText":"yes","noText":"no"},"display":{"delay":10,"hide":20,"type":"slide","zone":"A","position":7,"scroll":1,"animation":1,"viewresults":1},"gui":{"loading":"LOADING RESULTS","branding":"POWERED BY VIZU","viewPrivacy":"VIEW PRIVACY POLICY","safeAnonymous":"SAFE &amp; ANONYMOUS"},"poll":{"border":"cccccc","color":"000000","results":1,"resultstext":"Thank you for participating.<br><br>Your response helps keep<br>content free on the Web.","calltoactionsingle":"select one answer","calltoactionmultiple":"select up to NUMBER answers","button":{"color":"ffffff","bg":"fe6a00","text":"VOTE TO SEE RESULTS"}}},"ntag":{"enable":0,"FBnoRedirect":"","UScampaign":1,"OCR":1}};if(typeof dataObj1.tag==ud){var e={};throw(e);}}catch(e){e.code=1;e.message='dataObj1 is empty';throw(e);}
var VIZU;try{if(typeof w.top.VIZU==ud){w.top.vizu={};w.top.vizu.x=0;VIZU=w.top.VIZU={};}else{VIZU=w.top.VIZU;}
perm=true;d=w.top.document;if(w.top!=w){fiframe=true;}}catch(e){iframe=1;if(typeof w.VIZU!='object'){VIZU=w.VIZU={};}else{VIZU=w.VIZU;}
perm=false;}
try{qtags=dataObj1.tag.qtags;viewableEnabled=dataObj1.tag.viewableImpression;if(!VIZU.run){VIZU.run=[];}
VIZU.run[id]={};VIZUTEST=VIZU.run[id];}catch(e){e.code=2;throw(e);}
VIZU.run[id].crunchEnvironment=function(){return os.charAt(0)+os.charAt(os.length-1)+u.agent.substring(0,2)+u.ver.toString().substring(0,2)+u.lang.substring(0,2)+u.platform.charAt(0)+u.platform.charAt(u.platform.length-1)+u.uimode.charAt(0)+u.snapmode.charAt(0)+u.mobile.toString().charAt(0)+fv.toString().substring(0,2);}
try{var re=new RegExp('^(?:f|ht)tp(?:s)?://([^/]+)','im');try{if(w.parent!=w&&(d.referrer!=''||d.referrer.length!=0)){nest=true;}
nest?l=d.referrer.match(re)[1].toString():l=w.location.host.substring(0,1000);}catch(e){nest=true;l=w.location.host.substring(0,1000);}
if(ua==''&&edge_ua!=''){ua=edge_ua.toLowerCase();}
if(edge_lang!=''){lang=edge_lang;}
u.agent=(/msie/.test(ua)&&!/opera/.test(ua)&&!/aol/.test(ua))||/trident\/7/.test(ua)?'msie':/msie/.test(ua)&&/aol/.test(ua)?'aol':/firefox/.test(ua)&&!/(compatible|webkit)/.test(ua)?'ff':/webkit/.test(ua)&&/(chrome)/.test(ua)?'chrome':/webkit/.test(ua)&&!/(chrome)/.test(ua)?'safari':/opera/.test(ua)?'opera':'other';u.ver=(ua.match(/.+(?:fox|version|msie|chrome|webkit|opera|rv)[\/: ]([\d.]+)/))!=null?(ua.match(/.+(?:fox|version|msie|chrome|webkit|opera|rv)[\/: ]([\d.]+)/))[1]:0;u.lang=lang;u.platform=ua.match(/ipad/i)?'ipad':'other';ua.search('windows nt 6.3')!=-1?os='win8':ua.search('windows nt 6.2')!=-1?os='win8':ua.search('windows nt 6.1')!=-1?os='win7':ua.search('windows nt 6.0')!=-1?os='winv':ua.search('windows nt 5.1')!=-1?os='winxp':ua.search('mac')!=-1?os='mac':ua.search('linux')!=-1?os='linux':os='other';u.uimode='desktop';u.snapmode='none';u.mobile=false;if(typeof window.outerWidth!='undefined'){var sw=Math.floor(screen.width),sh=Math.floor(screen.height),ow=Math.floor(window.outerWidth),iw=Math.floor(window.innerWidth);if(os=='win8'){if(ua.match(/tablet pc/i)&&ua.match(/trident\/6/i)&&ua.match(/arm/i)&&ua.match(/touch/i)&&(sw==1366||(sw==768&&sh==1366))){u.platform='surface';}
if(u.agent=='msie'&&((ow==sw&&iw==sw)||(ow==sw-342&&iw==sw-342)||((ow==320||ow==768)&&iw==1024))){u.uimode='metro';u.platform+='.m';}else{u.platform+='.d';}
if(u.uimode=='metro'){if(ow==sw-342&&iw==sw-342){u.snapmode='large';}
if(ow==320&&iw==1024){u.snapmode='small';}}else{if(ow==sw-326&&iw==sw-342){u.snapmode='large';}}}}
if(u.platform=='ipad'&&u.agent=='safari'){useLocalStorage=true;u.mobile=true;}
if((u.agent=='safari'&&os=='linux')||(u.agent=='safari'&&ua.match(/iphone/i))){u.mobile=true;}
environment=VIZU.run[id].crunchEnvironment();}catch(e){e.code=3;throw(e);}
try{var _ios,blockIOSreturn=false;$VIZU6T.receiveMessage(function(m){var s=m.data.split('|');if(s[0]==id){if(u.agent=='msie'&&u.ver<8&&s[1]=='surveylaunch'){if(iframe==0&&!fiframe){d.location.hash=s[3];}else{window.document.location.hash=s[3];}}
if(s[1]=='ios'&&!blockIOSreturn){clearTimeout(_ios);if(s[2]=='storagefailed'){VIZU.run[id].img();VIZU.run[id].clear();}else{var x=unescape(s[2]);var y=x.split(';');VZ_anonID=y[0];guid=VZ_anonID;impcnt=y[1];VZ_t=y[2];VZ_s=y[3];VZ_opt_out=y[4];preexp=y[5];VIZU.run[id].exclude();}}
if(s[1]=='surveylaunch'){if(s[2]=='approved'){VIZU.run[id].loadSurvey();}
if(s[2]=='denied'){VIZU.run[id].clear();}}}});}catch(e){e.code=e.code?e.code:e.code=356;var i=d.createElement("img");i.style.display="none";d.body.insertBefore(i,d.body.lastChild);i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));VIZU.run[id].img();}
VIZU.run[id].domDetection=function(){if(dflag==0){dflag=1;_i=setInterval(function(){try{if(d.getElementsByTagName('body')[0]||d.body){clearInterval(_i);_i=null;clearTimeout(_t);if(viewableEnabled==1&&typeof VIZU.run[id].viewable=='function'){visible=0;if(VIZU.run[id].viewableBrowserSpec()){agifLocked=true;viewableDiv=document.createElement('div');}}
if(useLocalStorage){storageFrameTarget=base_static+'v6/htm/storageframe.html?id='+id+';guid='+guid+';vzcid='+vzcid+';pid='+pid+';adtype='+adtype+';vzadid='+vzadid+';ttype=7;vzsid='+vzsid+';siteurl='+window.location.hostname+';origin='+w.location.protocol+'//'+w.location.hostname+escape(w.location.pathname);VIZU.run[id].iframe(storageFrameTarget,'VIZUSTORAGE'+id);var h=d.documentElement.scrollHeight;var iosWait=30000;if(h>5000)iosWait=60000;if(h>10000)iosWait=120000;_ios=setTimeout(function(){blockIOSreturn=true;var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code=27&msg=storageframe%20never%20returned%20with%20data%20'+h+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);VIZU.run[id].img();VIZU.run[id].clear();},iosWait);}else{VIZU.run[id].exclude();}}}catch(e){clearInterval(_i);e.code=e.code?e.code:e.code=7;var i=d.createElement("img");i.style.display="none";d.body.insertBefore(i,d.body.lastChild);i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));VIZU.run[id].img();}},10);var domReadyWait=3000;if(useLocalStorage){domReadyWait=10000;}
var _t=setTimeout(function(){if(_i!=null){clearInterval(_i);var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code=8&msg=body%20was%20not%20found&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);VIZU.run[id].img();VIZU.run[id].clear();}},domReadyWait);}}
try{var hidden='undefined',visibilityChange;if(typeof document.hidden!=='undefined'){hidden='hidden';visibilityChange='visibilitychange';}else if(typeof document.mozHidden!=='undefined'){hidden='mozHidden';visibilityChange='mozvisibilitychange';}else if(typeof document.msHidden!=='undefined'){hidden='msHidden';visibilityChange='msvisibilitychange';}else if(typeof document.webkitHidden!=='undefined'){hidden='webkitHidden';visibilityChange='webkitvisibilitychange';}}catch(e){e.code=e.code?e.code:e.code=350;var i=d.createElement("img");i.style.display="none";d.body.insertBefore(i,d.body.lastChild);i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));VIZU.run[id].img();}
try{if(hidden!='undefined'){if(document[hidden]){document.addEventListener(visibilityChange,function(){if(!document[hidden]){VIZU.run[id].domDetection();}},false);}else{VIZU.run[id].domDetection();}}else{VIZU.run[id].domDetection();}}catch(e){e.code=e.code?e.code:e.code=351;var i=d.createElement("img");i.style.display="none";d.body.insertBefore(i,d.body.lastChild);i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));VIZU.run[id].img();}
VIZU.run[id].insert=function(x){try{d.body.insertBefore(x,d.body.firstChild);}catch(e){e.code=9;throw(e);}}
VIZU.run[id].img=function(type){try{var lock=false;if(type==null&&agifLocked){agifPrimed=true;}
if(type=='vi'&&!agifPrimed){lock=true;}
if(agifLocked){lock=true;}
if(!lock){var i=d.createElement('img');var tmp_adtype=adtype;if(type=='resend'){tmp_adtype=0;}
var params='vzcid='+vzcid+'&adtype='+tmp_adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&vzplid='+vzplid+'&vzwc='+vzwc+'&vzc1='+vzc1+'&vzc2='+vzc2+'&vzc3='+vzc3+'&vzc4='+vzc4+'&vzc5='+vzc5+'&vzc6='+vzc6+'&vzc7='+vzc7+'&vzc8='+vzc8+'&vzc9='+vzc9+'&vzc10='+vzc10+'&pass='+pass+'&iframe='+iframe+'&vzwt='+vzwt+'&vzsize='+environment+'&vztc='+id+'&visible='+visible;if(useLocalStorage){params+='&guid='+guid+'&preexp='+preexp+'&postexp='+postexp+'&impcnt='+impcnt;}
if(type=='opt-out'&&useLocalStorage){params+='&optout=1';}
if(!useLocalStorage&&pass==0){params+='&guid=unsupported';}
if(guidOverride!=''&&params.indexOf('guid')==-1){params+='&guid='+guid;}
params+='&exptime=';i.setAttribute('src',base_adpix+'a.gif?'+params+'&_t='+id+'.'+Math.floor(100+Math.random()*900));i.style.display='none';if(aflag==0||type=='resend'){aflag=1;VIZU.run[id].insert(i);if(useLocalStorage&&adtype==1&&type!='opt-out'){var storageFrameHandle=window.document.getElementById('VIZUSTORAGE'+id).contentWindow;$VIZU6T.postMessage(id+'|testimpression|'+vzcid,storageFrameTarget,storageFrameHandle);}}}}catch(e){e.code=e.code?e.code:e.code=11;throw(e);}}
VIZU.run[id].script=function(url,callBack,vars){try{var x=d.createElement('script');x.setAttribute('type','text/javascript');x.src=url;var done=0;x.onload=x.onreadystatechange=function(){if(!done&&(!this.readyState||this.readyState==='loaded'||this.readyState==='complete')){done=true;if(typeof callBack=='function'){callBack(vars);}}};VIZU.run[id].insert(x);}catch(e){e.code=e.code?e.code:e.code=12;throw(e);}}
VIZU.run[id].iframe=function(url,ifname){try{if(ifname=='passframe'||ifname.indexOf('VIZUSTORAGE')!=-1||ifname.indexOf('VIZUCONTROLLER')!=-1){var x=window.document.createElement('iframe');}else{var x=d.createElement('iframe');}
x.style.width='1px';x.style.height='1px';x.style.position='absolute';x.style.top='-7px';x.src=url;if(ifname=='passframe'||ifname.indexOf('VIZUSTORAGE')!=-1||ifname.indexOf('VIZUCONTROLLER')!=-1){window.document.body.insertBefore(x,window.document.body.firstChild);}else{VIZU.run[id].insert(x);}
if(ifname==''){ifname='VIZU'+Math.floor(Math.random()*1000000);}
x.setAttribute('id',ifname);}catch(e){e.code=e.code?e.code:e.code=13;throw(e);}}
VIZU.run[id].adjustState=function(){try{postexp=adtype;impcnt=Math.floor(impcnt)+Math.floor(adtype);}catch(e){e.code=e.code?e.code:e.code=224;throw(e);}};VIZU.run[id].get3pt=function(){try{var params='vzcid='+vzcid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&vzplid='+vzplid+'&vzwc='+vzwc+'&vzc1='+vzc1+'&vzc2='+vzc2+'&vzc3='+vzc3+'&vzc4='+vzc4+'&vzc5='+vzc5+'&vzc6='+vzc6+'&vzc7='+vzc7+'&vzc8='+vzc8+'&vzc9='+vzc9+'&vzc10='+vzc10+'&iframe='+iframe+'&vzwt='+vzwt+'&vzsize='+vzsize+'&vztc='+vztc+'&visible='+visible+'&preexp='+preexp+'&postexp='+postexp+'&impcnt='+impcnt+'&os='+os+'&ua='+u.agent+'&uv='+u.ver+'&id='+id+'&pid=&uid='+guid+'&aid=null&t='+new Date().getTime();if(dataObj1.tag.ctags[0]=="1"){VIZU.run[id].iframe(base_static+"cdn/"+path+"3pt/ai.htm?"+params,'');}}catch(e){e.code=e.code?e.code:e.code=14;throw(e);}};VIZU.run[id].adjustAM=function(){try{if(!isNaN(parseFloat(vzam))&&isFinite(vzam)){if(vzam<10000){vzam=Math.floor(vzam)+10000;}}}catch(e){e.code=e.code?e.code:e.code=397;throw(e);}};VIZU.run[id].insertNTag=function(){try{var p=node.parentNode;var ntag='';var fbno=dataObj1.ntag.FBnoRedirect;if(fbno!=''){if(fbno.indexOf(',')!=-1){fbno=fbno.split(',');for(var i=0;i<fbno.length;i++){if(fbno[i]==vzsid){VIZU.run[id].adjustAM();}}}else{if(fbno==vzsid){VIZU.run[id].adjustAM();}}}
ntag+=n_url_tag;ntag+='?ci='+n_acctID;if(dataObj1.ntag.OCR==1){ntag+='&am='+vzam;ntag+='&mr='+n_mr;ntag+='&ty='+n_ty;}
ntag+='&at=view';ntag+='&rt=banner';ntag+='&st=image';ntag+='&ca=nlsn'+vzcid;ntag+='&cr='+vzadid;if(vzplid!=''){ntag+='&pc='+vzplid;}else{ntag+='&pc='+vzsid;if(vzwc!=''){ntag+='_'+vzwc;}}
ntag+='&ce='+vzsid;ntag+='&r='+id;var x=d.createElement('script');x.setAttribute('type','text/javascript');x.src=ntag;p.insertBefore(x,p.firstChild);}catch(e){e.code=e.code?e.code:e.code=395;throw(e);}};VIZU.run[id].matchAdSize=function(adW,adH){try{var banType,psaSize;adW>=300&&adH>=250?banType='300x250':adW>=160&&adH>=600?banType='160x600':banType=null;adW==300&&adH==250?psaSize='300x250':adW==160&&adH==600?psaSize='160x600':adW==728&&adH==90?psaSize='728x90':adW==300&&adH==600?psaSize='300x600':adW==120&&adH==600?psaSize='120x600':psaSize=null;if(psaSize==null&&adW>=300&&adH>=250){psaSize='300x250';}
if(psaSize==null&&adW>=728&&adH>=90){psaSize='728x90';}
return[banType,psaSize];}catch(e){e.code=e.code?e.code:e.code=394;throw(e);}}
VIZU.run[id].getAdSize=function(viOnly){try{var adW=0,adH=0,banType,psaSize,children,pNode=node.parentNode,checkDivLater=false;for(var i=0;i<dataObj1.tag.sIntLevel;i++){pNode=pNode.parentNode;}
var _b=setInterval(function(){try{children=pNode.childNodes.length;for(var i=0;i<children;i++){var child=pNode.childNodes[i];if(child!=null&&child.nodeType==1&&child.nodeName.toLowerCase()!='script'){contentNodes++;if(child.offsetWidth>1||child.offsetHeight>1){clearInterval(_b);_b=null;adW=child.offsetWidth;if(child.nodeName.toLowerCase()=='object'&&(u.agent=='ff'||u.agent=='chrome')){adH=child.height;}else{adH=child.offsetHeight;if(adH==0&&child.nodeName.toLowerCase()=='div'){if(child.childNodes.length>0){if(child.childNodes[0].nodeName.toLowerCase()=='object'){adH=child.childNodes[0].offsetHeight;}}else{checkDivLater=true;}}}
if(child.nodeName.toLowerCase()=='a'&&adH<90){for(var m=0;m<child.childNodes.length;m++){if(child.childNodes[m].offsetHeight>=90){adH=child.childNodes[m].offsetHeight;break;}}}
var sizes=VIZU.run[id].matchAdSize(adW,adH);banType=sizes[0];psaSize=sizes[1];if(banType||psaSize){break;}}}}
if(!_b){_b2=setTimeout(function(){if(adH==0){if(checkDivLater){var d1=pNode.innerHTML.search(/[^-]height[\:|\=][ ]?[\'|\"]?[\d]*/g);if(d1!=-1){var d2=d1+15;var fragment=pNode.innerHTML.substring(d1,d2);d1=fragment.search(/\d+/g);fragment=fragment.substring(d1,fragment.length);d1=fragment.search(/[^\d+]/g);fragment=fragment.substring(0,d1);if(!isNaN(parseFloat(fragment))&&isFinite(fragment)){adH=fragment;var sizes=VIZU.run[id].matchAdSize(adW,adH);banType=sizes[0];psaSize=sizes[1];}}}
if(adH==0){var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code=392&msg=adH is still 0 after ad height detection&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);}}
if(!viOnly){VIZU.run[id].main({'adW':adW,'adH':adH,'banType':banType,'pNode':pNode,'psaSize':psaSize});}
if(viewableEnabled==1){if(typeof VIZU.run[id].viewable=='function'){VIZU.run[id].viewable(pNode,adW,adH);}}},10);}}catch(e){clearInterval(_b);e.code=e.code?e.code:e.code=15;var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);if(aflag==0){aflag=1;var i=d.createElement('img'),params='vzcid='+vzcid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&vzplid='+vzplid+'&vzwc='+vzwc+'&vzc1='+vzc1+'&vzc2='+vzc2+'&vzc3='+vzc3+'&vzc4='+vzc4+'&vzc5='+vzc5+'&vzc6='+vzc6+'&vzc7='+vzc7+'&vzc8='+vzc8+'&vzc9='+vzc9+'&vzc10='+vzc10+'&pass='+pass+'&iframe='+iframe+'&vzwt='+vzwt+'&vzsize='+vzsize+'&vztc='+vztc+'&visible='+visible;i.setAttribute('src',base_adpix+'a.gif?'+params+'&_t='+id);i.style.display='none';d.body.insertBefore(i,d.body.lastChild);}}},10);var t=setTimeout(function(){if(_b){try{clearInterval(_b);if(!viOnly){agifLocked=false;VIZU.run[id].main({'adW':adW,'adH':adH,'banType':banType,'pNode':pNode,'psaSize':psaSize});}}catch(e){e.code=e.code?e.code:e.code=25;var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);VIZU.run[id].img();}}},1000);}catch(e){e.code=e.code?e.code:e.code=23;throw(e);}}
VIZU.run[id].exclude=function(){try{var excluded=false,i,viOnly=false;if(VZ_opt_out=='true'){VIZU.run[id].adjustState();if(viewableEnabled==0){agifLocked=false;VIZU.run[id].img('opt-out');}else{viOnly=true;agifPrimed=true;}
excluded=true;}
if(!VIZU.run[id].browserSpec()&&!excluded){VIZU.run[id].adjustState();VIZU.run[id].get3pt();pass=0;agifLocked=false;VIZU.run[id].img();excluded=true;}
if(dataObj1.tag.sIntType=='flyover'){try{if(!excluded){for(i=0;i<dataObj1.tag.siteBlacklist.length;i++){if(w.location.hostname.toLowerCase().search(dataObj1.tag.siteBlacklist[i])!=-1&&!excluded){VIZU.run[id].adjustState();VIZU.run[id].get3pt();if(viewableEnabled==0){agifLocked=false;}else{viOnly=true;}
VIZU.run[id].img();excluded=true;break;}}}
if(!excluded){for(var i=0;i<dataObj1.tag.sAdBlacklist.length;i++){if((dataObj1.tag.sAdBlacklist[i]==vzadid||dataObj1.tag.sAdBlacklist[i]==vzplid)&&!excluded){VIZU.run[id].adjustState();VIZU.run[id].get3pt();if(viewableEnabled==0){agifLocked=false;}else{viOnly=true;}
VIZU.run[id].img();excluded=true;break;}}}
if(!excluded){if(VZ_t!=''&&!excluded){VIZU.run[id].adjustState();VIZU.run[id].get3pt();if(viewableEnabled==0){agifLocked=false;}else{viOnly=true;}
VIZU.run[id].img();excluded=true;}}}catch(e){e.code=e.code?e.code:e.code=20;throw(e);}}
var tmptags=[],t=0;for(i in qtags){if(qtags.hasOwnProperty(i)){if((dataObj1.tag.sIntType=='flyover'&&VZ_s.indexOf(qtags[i].id+'-')==-1)||(dataObj1.tag.sIntType=='banner'&&(VZ_s.indexOf(qtags[i].id+'-')==-1||VZ_s.indexOf(qtags[i].id+'-0')!=-1))){tmptags[t++]=qtags[i];}}}
qtags=tmptags;if(qtags.length==0&&!excluded){VIZU.run[id].adjustState();VIZU.run[id].get3pt();if(viewableEnabled==0){agifLocked=false;}else{viOnly=true;}
VIZU.run[id].img();excluded=true;}
try{if(excluded&&dataObj1.ntag.enable==1&&VZ_opt_out!='true'){VIZU.run[id].insertNTag();}}catch(e){e.code=396;e.message='V7 tag encountered V6 dataobject ntag not found';throw(e);}
if(!excluded||viOnly){VIZU.run[id].getAdSize(viOnly);}else{VIZU.run[id].clear();}}catch(e){e.code=e.code?e.code:e.code=21;throw(e);}}
VIZU.run[id].browserSpec=function(){try{var bpass=false;if(os=='winxp'||os=='winv'||os=='win7'||os=='win8'||os=='mac'){if(u.agent=='ff'&&parseFloat(u.ver)>=3.6){bpass=true;}
if(u.agent=='msie'&&parseFloat(u.ver)>=6){bpass=true;if(u.snapmode=='small'){bpass=false;}}
if(u.agent=='chrome'&&parseFloat(u.ver)>=10){bpass=true;}
if(u.agent=='aol'&&parseFloat(u.ver)>=7){bpass=true;}
if(u.platform=='ipad'&&u.agent=='safari'&&dataObj1.tag.mobile==1){bpass=true;}}
return bpass;}catch(e){e.code=19;throw(e);}}
VIZU.run[id].main=function(v){try{var current_intT=0,current_intC=0;if((dataObj1.tag.sIntType=="banner"&&v.banType)||(dataObj1.tag.sIntType=="flyover"&&(perm||dataObj1.tag.busterurl!=''))){if((dataObj1.tag.sIntType=="banner"&&(v.pNode.nodeName.toLowerCase()!="body"||nest))||dataObj1.tag.sIntType=="flyover"){current_intT=dataObj1.tag.sIntT;}
if((v.adW>1||v.adH>1)&&(v.pNode.nodeName.toLowerCase()!="body"||nest||(w.parent!=w&&contentNodes==1&&typeof v.psaSize!="undefined"))){current_intC=dataObj1.tag.sIntC;}}
if(impcnt==0){if(current_intC>0&&Math.random()<=current_intC){VIZU.run[id].survey(v.adW,v.adH,v.banType,v.pNode,0,v.psaSize);}else{try{if(dataObj1.ntag.enable==1){VIZU.run[id].insertNTag();}}catch(e){e.code=396;e.message='V7 tag encountered V6 dataobject ntag not found';throw(e);}
if(current_intT>0&&Math.random()<=current_intT){VIZU.run[id].survey(v.adW,v.adH,v.banType,v.pNode,1,v.psaSize);}else{VIZU.run[id].adjustState();VIZU.run[id].get3pt();VIZU.run[id].img();VIZU.run[id].clear();}}}else{try{if(dataObj1.ntag.enable==1){VIZU.run[id].insertNTag();}}catch(e){e.code=396;e.message='V7 tag encountered V6 dataobject ntag not found';throw(e);}
postexp=1;if(current_intT>0&&Math.random()<=current_intT){VIZU.run[id].survey(v.adW,v.adH,v.banType,v.pNode,1,v.psaSize);}else{VIZU.run[id].adjustState();VIZU.run[id].get3pt();VIZU.run[id].img();VIZU.run[id].clear();}}}catch(e){e.code=e.code?e.code:e.code=22;throw(e);}}
VIZU.run[id].vars=function(){var vzclicktmp='';if(vzclick!=''){vzclicktmp='&vzclick='+vzclick;}
var v='vzcid='+vzcid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&vzplid='+vzplid+'&vzwc='+vzwc+'&vzc1='+vzc1+'&vzc2='+vzc2+'&vzc3='+vzc3+'&vzc4='+vzc4+'&vzc5='+vzc5+'&vzc6='+vzc6+'&vzc7='+vzc7+'&vzc8='+vzc8+'&vzc9='+vzc9+'&vzc10='+vzc10+'&iframe='+iframe+'&vzwt='+vzwt+'&vzsize='+vzsize+'&vztc='+vztc+'&visible='+visible+'&preexp='+preexp+'&postexp='+postexp+'&impcnt='+impcnt+'&os='+os+'&ua='+u.agent+'&uv='+u.ver+'&useLocalStorage='+useLocalStorage+'&platform='+environment+'&id='+id+'&pid='+pid+vzclicktmp;if(useLocalStorage){v+='&guid='+guid;}
if(guidOverride!=''&&v.indexOf('guid')==-1){v+='&guid='+guid;}
return v;}
VIZU.run[id].survey=function(adW,adH,banType,pNode,exposure_state,psaSize){try{pNode.style.width=adW+'px';pNode.style.height=adH+'px';var r=Math.floor(Math.random()*qtags.length);var c=0;for(var c in qtags){if(qtags.hasOwnProperty(c)){if(c==r){pid=qtags[c].id;break;}}}
function hide(){try{var len=pNode.childNodes.length,kids=pNode.childNodes;for(var i=0;i<len;i++){if(kids[i]!=null&&kids[i].nodeType==1&&kids[i].id!='VIZUVI'){kids[i].style.visibility='hidden';}}
for(var i=0;i<len;i++){if(kids[i]!=null&&kids[i].nodeType==1&&kids[i].id!='VIZUVI'){kids[i].style.display='none';}}}catch(e){e.code=4;throw(e);}}
function banner(){try{if(u.agent=='msie'&&u.ver<8&&fiframe){var x=window.document.createElement('div');}else{var x=d.createElement('div');}
bannerURL=base_dynamic+'cdn/'+path+banType+'_survey_st.html?'+VIZU.run[id].vars();x.innerHTML='<iframe id="VIZUSURVEYBANNER'+id+'" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" style="width: '+adW+'px; height: '+adH+'px;" src="'+bannerURL+'"></iframe>';pNode.appendChild(x);bannerUp=true;}catch(e){e.code=5;throw(e);}}
function psa(){try{var randNum=Math.floor(Math.random()*psaObj[psaSize].length);if(u.agent=='msie'&&u.ver<8&&pNode.nodeName.toLowerCase()=='body'){var a=pNode.parentNode.parentNode.createElement('a');a.href=psaObj[psaSize][randNum].href;a.target='_blank';pNode.parentNode.parentNode.appendChild(a);var img=pNode.parentNode.parentNode.createElement('img');img.setAttribute('src',psaObj[psaSize][randNum].src);img.style.border="0";a.appendChild(img);}else{var a=d.createElement('a');a.href=psaObj[psaSize][randNum].href;a.target='_blank';pNode.appendChild(a);var img=d.createElement('img');img.setAttribute('src',psaObj[psaSize][randNum].src);img.style.border="0";a.appendChild(img);}
a.style.display='block';a.style.margin='auto';}catch(e){e.code=e.code?e.code:e.code=17;throw(e)}}
if(dataObj1.tag.sIntType=='banner'){if(banType=='300x250'){ttype=9;}else{ttype=8;}}
if(dataObj1.tag.sIntType=='flyover'){try{if(typeof VIZU.intercept==ud){VIZU.intercept=true;if(exposure_state==0){adtype=0;hide();if(psaSize){psa();}}
if(u.agent=='msie'&&u.ver<8){VIZU.run[id].loadSurvey();}else{VIZU.run[id].iframe(passtarget+'?vzcid='+vzcid+';pid='+pid+';adtype='+adtype+';vzadid='+vzadid+';ttype='+ttype+';vzsid='+vzsid+';platform='+u.platform+';useLocalStorage='+useLocalStorage+';siteurl='+window.location.hostname+';id='+id+';basepoll='+base_static+'cdn/'+path+';origin='+w.location.protocol+'//'+w.location.hostname+escape(w.location.pathname)+escape(w.location.search),'passframe');}
VIZU.run[id].adjustState();VIZU.run[id].get3pt();VIZU.run[id].img();}else{VIZU.run[id].adjustState();if(dataObj1.ntag.enable==1){VIZU.run[id].insertNTag();}
VIZU.run[id].get3pt();VIZU.run[id].img();VIZU.run[id].clear();}}catch(e){e.code=e.code?e.code:e.code=6;throw(e);}}else{var time=0;if(exposure_state=='0'){adtype=0;}else{time=15000;}
VIZU.run[id].adjustState();VIZU.run[id].get3pt();VIZU.run[id].img();var _t=setTimeout(function(){try{hide();banner();VIZU.run[id].clear();}catch(e){e.code=e.code?e.code:e.code=24;var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);VIZU.run[id].img();}},time);}}catch(e){e.code=e.code?e.code:e.code=16;throw(e);}}
VIZU.run[id].loadSurvey=function(){var _slt=setTimeout(function(){try{if(perm){VIZU.run[id].script(base_dynamic+"cdn/"+path+'survey.js?'+VIZU.run[id].vars(),'');}else{var ref=d.referrer.split('.'),bsa=dataObj1.tag.busterurl.split('.');if(bsa[0]!=ref[0]&&d.referrer!=''){bsa[0]=ref[0];}
VIZU.run[id].iframe(bsa.join('.')+'?ifile='+base_static+'v6/js/buster.js?'+VIZU.run[id].vars()+'&base='+base_dynamic+'&path='+path,'');}
VIZU.run[id].clear();}catch(e){e.code=e.code?e.code:e.code=266;var i=d.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'e.gif?vzcid='+vzcid+'&pid='+pid+'&adtype='+adtype+'&vzadid='+vzadid+'&ttype=7&vzsid='+vzsid+'&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&scripturl='+escape(s.src).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));d.body.insertBefore(i,d.body.lastChild);VIZU.run[id].img();}},5000);}
VIZU.run[id].clear=function(){try{if(viewableEnabled==0){qtags=[];dataObj1={};}}catch(e){e.code=e.code?e.code:e.code=18;throw(e);}}}catch(e){e.code=e.code?e.code:e.code=220;var base_adpix='http://ohlone.vizu.com';var base_error='http://kato.vizu.com';if(window.location.protocol=='https:'){base_adpix=base_adpix.replace(/http:/g,"https:");base_error=base_error.replace(/http:/g,"https:");}
if(aflag==0){aflag=1;if(typeof visible=='undefined'){visible=4;}
if(visible==2){visible=5;}
var i=window.document.createElement('img'),params='vzcid=12264&adtype='+adtype+'&vzadid=fy15chefboyardee300x250&ttype=7&vzsid=rocketfuel&siteurl='+window.location.hostname+'&vzplid=&vzwc=&vzc1=&vzc2=&vzc3=&vzc4=&vzc5=&vzc6=&vzc7=&vzc8=&vzc9=&vzc10=&pass='+pass+'&iframe='+iframe+'&vzwt=&vzsize='+environment+'&vztc=&visible='+visible;i.setAttribute('src',base_adpix+'/a.gif?'+params+'&_t='+id);i.style.display='none';window.document.body.insertBefore(i,window.document.body.lastChild);}
var i=window.document.createElement('img');i.style.display='none';i.setAttribute('src',base_error+'/e.gif?vzcid=12264&pid='+pid+'&adtype='+adtype+'&vzadid=fy15chefboyardee300x250&ttype=1&vzsid=rocketfuel&siteurl='+window.location.hostname+'&code='+e.code+'&msg='+escape(e.message).substring(0,1000)+'&referrer='+escape(l).substring(0,1000));window.document.body.insertBefore(i,window.document.body.lastChild);}})(window);